### ISSUE TITLE
Syntax error

### ISSUE THREAD

**Issue by nsjithin** [OpusCapita/react-signalr#4]
```
./src/app.jsx
Syntax error: Unexpected token (28:0)

  26 | }
  27 | 
> 28 | @injectSignalR({
     | ^
  29 |   // Defines both the last part of the route to the hub,
  30 |   // and also the key of the hub proxy in this.props.
  31 |   // In this case it hub proxy is found in this.props.mynotifier.
```

I am getting a syntax error when trying to use this module. I am newbie and not sure I am doing it right?

**Comment by zjuice** [comment]
The @-character is a special character defining a decorator. Please, see e.g. [this solution](https://stackoverflow.com/questions/43492086/unexpected-token-when-using-babel-decorator) on StackOverflow.

You may also use this as a HOC like this
```jsx
class MyComponent {
  // ...
}

export default injectSignalR({ 
  // ...
})(MyComponent);
 ```
